Search_Input_Field = "xpath = //input [@id='search_query_top']"
Search_Button = "xpath = //button [@name='submit_search']"
Mouse_Over_Women_Section = "xpath = //a [@title='Women']"
Click_Over_Blouses = "xpath = //a [@ title = 'Blouses']"
Contains_Text_Blouses = "xpath = //h1[contains(@class,  Blouses)]"
