
Sign_in_button = "xpath = //a[@title='Log in to your customer account']"
Input_field_email_create_an_account = "xpath = //input[@id='email_create']"
Create_account_button = "xpath = //button[@name='SubmitCreate']"
First_name_input_registration = "xpath = //input[@id='customer_firstname']"
UR_Personal_Info = "xpath =//h3[@class='page-subheading']"
Last_name_input_registration = "xpath = //input[@id='customer_lastname']"
Email_create_account = "xpath = //input[@id='email']"
Passwd = "xpath = //input[@id = 'passwd']"
Address = "xpath = //input[@id='address1']"
City_locator = "xpath = //input[@id='city']"
dropdown_index = "xpath = //select[@id='id_state']"
PostCode_locator = "xpath = //input[@id='postcode']"
Mobile_locator = "xpath = //input[@id='phone_mobile']"
Register_button_locator = "xpath = //button[@id = 'submitAccount']"
Register_not_successful_error = "xpath = //div [@class= 'alert alert-danger']"